"""
Build model.joblib artifact for YMINSIGHT Lambda deployment.

Usage:
    python build_model_artifact.py

Outputs:
    model.joblib          - serialized HybridModel for Lambda inference
    requirements.txt      - exact dependency versions for Lambda image

Then upload:
    aws s3 cp model.joblib s3://yminsight-processed-data/models/model.joblib
    aws s3 cp requirements.txt s3://yminsight-processed-data/models/requirements.txt
"""

import sys
import subprocess
import importlib.metadata
from pathlib import Path

import joblib
import numpy as np
import pandas as pd

# Make sure the repo root is on sys.path so `from lambdas.etl import handler`
# and `from ml.training import model` both resolve correctly.
REPO_ROOT = Path(__file__).resolve().parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from lambdas.etl.handler import run_etl
from ml.training import model as M
from ml.training.validation import mape


# ─── 1. Load raw CSVs (dtype=str to preserve HIDDEN/PREDICT markers) ──────────

RAW = REPO_ROOT / "data" / "raw"
print("Loading raw CSVs…")
voyage_df      = pd.read_csv(RAW / "vt_fd.csv",       dtype=str)
maintenance_df = pd.read_csv(RAW / "maintenance.csv",  dtype=str)

# ─── 2. ETL ───────────────────────────────────────────────────────────────────

print("Running ETL pipeline…")
clean = run_etl(voyage_df, maintenance_df)
clean = M.add_derived(clean)

n_predict = int(clean["predict_fuel"].notna().sum())
n_train   = int(M.train_mask(clean).sum())
print(f"  Total rows   : {len(clean):,}")
print(f"  Training rows: {n_train:,}")
print(f"  PREDICT rows : {n_predict}")

# ─── 3. Train ─────────────────────────────────────────────────────────────────

print("Training HybridModel…")
fitted_model = M.train(clean)
print(f"  Admiralty backbone  a={fitted_model.a:.4f}  b={fitted_model.b:.4f}")

# ─── 4. Sanity-check against ml/examples/submission.csv ──────────────────────

print("Running sanity check against ml/examples/submission.csv…")
submission = M.predict_submission(fitted_model, clean)

EXAMPLE = REPO_ROOT / "ml" / "examples" / "submission.csv"
reference = pd.read_csv(EXAMPLE)

# Align on (ship_id, day, fuel_type) for comparison
merged = submission.merge(
    reference.rename(columns={"predicted_value": "ref_value"}),
    on=["ship_id", "day", "fuel_type"],
    how="inner",
)

if len(merged) == 0:
    print("  WARNING: no rows matched reference — check column names")
elif len(merged) < n_predict:
    print(f"  WARNING: only {len(merged)}/{n_predict} rows matched reference")
else:
    mape_val = mape(merged["ref_value"].to_numpy(), merged["predicted_value"].to_numpy())
    print(f"  Matched {len(merged)} / {n_predict} PREDICT rows")
    print(f"  MAPE vs reference submission: {mape_val:.2f}%")
    if mape_val < 1.0:
        print("  ✓ Sanity check PASSED (MAPE < 1% vs reference)")
    else:
        print("  ! Sanity check: MAPE higher than expected — check ETL/model versions")

# ─── 5. Serialize model ───────────────────────────────────────────────────────

OUT_MODEL = REPO_ROOT / "model.joblib"
print(f"\nSerializing model → {OUT_MODEL}")
joblib.dump(fitted_model, OUT_MODEL, compress=3)
size_kb = OUT_MODEL.stat().st_size / 1024
print(f"  model.joblib size: {size_kb:.1f} KB")

# ─── 6. Write requirements.txt with exact pinned versions ────────────────────

PKGS = ["scikit-learn", "numpy", "pandas", "joblib", "pyarrow"]
lines = [f"# Auto-generated by build_model_artifact.py — Python {sys.version.split()[0]}"]
for pkg in PKGS:
    try:
        version = importlib.metadata.version(pkg)
        lines.append(f"{pkg}=={version}")
    except importlib.metadata.PackageNotFoundError:
        lines.append(f"# {pkg} not found in environment")

OUT_REQ = REPO_ROOT / "requirements.txt"
OUT_REQ.write_text("\n".join(lines) + "\n")
print(f"\nWrote {OUT_REQ}:")
for line in lines:
    print(f"  {line}")

# ─── 7. Done ──────────────────────────────────────────────────────────────────

print("\n✓ Artifact build complete.")
print("Next steps:")
print("  aws s3 cp model.joblib     s3://yminsight-processed-data/models/model.joblib")
print("  aws s3 cp requirements.txt s3://yminsight-processed-data/models/requirements.txt")
